### ISSUE TITLE
class Computer

### ISSUE THREAD

**Issue by grace-joh** [grace-joh/connect_four#10]
- [x] #initialize
- [x] #random_input

**Comment by grace-joh** [comment]
@margdaly 
I made a PR for #initialize ( #9 ) for now, so we can work on #random_input together!

**Comment by grace-joh** [comment]
https://www.rubyguides.com/2015/03/ruby-random/
found a method for getting a random letter!

**Comment by margdaly** [comment]
Let's add the second edge case for initialize together in Computer and Player

**Comment by margdaly** [comment]
check
